version: 1
disable_existing_loggers: False

formatters:
    standard_colored:
        (): logging_setup.CustomFormatterColored
    standard:
        (): logging_setup.CustomFormatter
filters:
    warning_filter:
        (): logging_setup.WarningFilter

handlers:
    stdout:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard_colored
        stream: ext://sys.stdout
        filters: [warning_filter]

    stderr:
        class: logging.StreamHandler
        level: ERROR
        formatter: standard_colored
        stream: ext://sys.stderr

    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: ./tmp/out.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    file_err:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: standard
        filename: ./tmp/err.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8


loggers:
    dev:
        level: DEBUG
        handlers: [file, file_err, stdout, stderr]
        propagate: no
    prod:
        level: INFO
        handlers: [file, file_err, stdout, stderr]
        propagate: no


root:
    level: INFO
    handlers: [stdout]